name: Build
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.0.100'
      - name: Build project
        run: dotnet build
      - name: Run tests
        run: dotnet test
